name: Deploy to VPS

on:
  push:
    branches:
      - deploy

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ vars.URL }}

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/pokesort
            git pull origin deploy
            npm ci
            npm run build
            pm2 restart 0